name: Atualizar Lista IPTV

on:
  schedule:
    - cron: '10 12 * * *' # Sugestão: 12:10 UTC (09:10 BRT) para evitar o "rush"
    
  workflow_dispatch: # Permite rodar manualmente com um clique

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependências
        run: pip install requests

      - name: Executar Script
        run: python update_list.py

      - name: Salvar Alterações
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add lista.m3u
          git commit -m "Lista atualizada automaticamente" || exit 0
          git push
